package com.mycompany.jaydee;


import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rica
 */
public class AddAccount extends javax.swing.JFrame {

    public AddAccount() {
        initComponents();
        
        
        ButtonGroup bg = new ButtonGroup(); 
        bg.add(jRadioButtonMale); 
        bg.add(jRadioButtonFemale);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
 
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldLastname = new javax.swing.JTextField();
        jTextFieldFirstname = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldPhonenum = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jTextFieldManager = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldProject = new javax.swing.JTextField();
        jDateChooserDue = new com.toedter.calendar.JDateChooser();
        jTextFieldUsername = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 1500));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(226, 226, 226));
        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(107, 0, 215));
        jLabel7.setText("Phone no :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(160, 270, 110, 40);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(107, 0, 215));
        jLabel9.setText("Email :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(160, 210, 110, 40);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(107, 0, 215));
        jLabel11.setText("First Name :");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(160, 30, 110, 40);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(107, 0, 215));
        jLabel8.setText("Last Name :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(160, 90, 110, 40);

        jTextFieldLastname.setBackground(new java.awt.Color(242, 242, 242));
        jTextFieldLastname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldLastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldLastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldLastnameFocusLost(evt);
            }
        });
        jTextFieldLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLastnameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldLastname);
        jTextFieldLastname.setBounds(300, 90, 300, 30);

        jTextFieldFirstname.setBackground(new java.awt.Color(242, 242, 242));
        jTextFieldFirstname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldFirstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldFirstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldFirstnameFocusLost(evt);
            }
        });
        jTextFieldFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFirstnameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldFirstname);
        jTextFieldFirstname.setBounds(300, 30, 300, 30);

        jTextFieldEmail.setBackground(new java.awt.Color(242, 242, 242));
        jTextFieldEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusLost(evt);
            }
        });
        jPanel2.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(300, 210, 300, 30);

        jTextFieldPhonenum.setBackground(new java.awt.Color(242, 242, 242));
        jTextFieldPhonenum.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jTextFieldPhonenum.setForeground(new java.awt.Color(107, 0, 215));
        jTextFieldPhonenum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPhonenumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPhonenumFocusLost(evt);
            }
        });
        jPanel2.add(jTextFieldPhonenum);
        jTextFieldPhonenum.setBounds(300, 270, 300, 30);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(107, 0, 215));
        jLabel13.setText("Gender :");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(160, 330, 90, 30);

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(107, 0, 215));
        jLabel14.setText("Manager :");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(160, 380, 110, 40);

        jButtonAdd.setBackground(new java.awt.Color(107, 0, 215));
        jButtonAdd.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd.setText("Add");
        jButtonAdd.setAutoscrolls(true);
        jButtonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAddMouseExited(evt);
            }
        });
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAdd);
        jButtonAdd.setBounds(340, 600, 220, 60);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setForeground(new java.awt.Color(178, 178, 178));
        jCheckBox1.setLabel("agree to terms and conditions.");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(360, 560, 190, 30);

        jRadioButtonMale.setForeground(new java.awt.Color(107, 0, 215));
        jRadioButtonMale.setText("Male");
        jRadioButtonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaleActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonMale);
        jRadioButtonMale.setBounds(300, 330, 50, 21);

        jRadioButtonFemale.setForeground(new java.awt.Color(107, 0, 215));
        jRadioButtonFemale.setText("Female");
        jPanel2.add(jRadioButtonFemale);
        jRadioButtonFemale.setBounds(380, 330, 70, 21);

        jTextFieldManager.setBackground(new java.awt.Color(242, 242, 242));
        jTextFieldManager.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jTextFieldManager.setForeground(new java.awt.Color(107, 0, 215));
        jTextFieldManager.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldManagerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldManagerFocusLost(evt);
            }
        });
        jPanel2.add(jTextFieldManager);
        jTextFieldManager.setBounds(300, 380, 300, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Coloring dark1 (1).jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(0, 700, 660, 240);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(107, 0, 215));
        jLabel10.setText("Project :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(160, 430, 70, 50);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(107, 0, 215));
        jLabel12.setText("Due-date :");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(160, 490, 90, 50);

        jTextFieldProject.setBackground(new java.awt.Color(242, 242, 242));
        jTextFieldProject.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jTextFieldProject.setForeground(new java.awt.Color(107, 0, 215));
        jTextFieldProject.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldProjectFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldProjectFocusLost(evt);
            }
        });
        jPanel2.add(jTextFieldProject);
        jTextFieldProject.setBounds(300, 440, 300, 30);
        jPanel2.add(jDateChooserDue);
        jDateChooserDue.setBounds(300, 500, 300, 30);

        jTextFieldUsername.setBackground(new java.awt.Color(242, 242, 242));
        jTextFieldUsername.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUsernameFocusLost(evt);
            }
        });
        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldUsername);
        jTextFieldUsername.setBounds(300, 150, 300, 30);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(107, 0, 215));
        jLabel2.setText("Add account!");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(380, 450, 200, 60);

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(140, 140, 140));
        jLabel3.setText("Opportunities don't happen, you create them");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(330, 530, 320, 20);

        jLabelLogin.setFont(new java.awt.Font("Calibri Light", 2, 13)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(107, 0, 215));
        jLabelLogin.setText("Back to Dashboard -->");
        jLabelLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseClicked(evt);
            }
        });
        jPanel3.add(jLabelLogin);
        jLabelLogin.setBounds(420, 620, 130, 17);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Add account!");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(380, 460, 210, 50);

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("___________________________________________________");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(340, 580, 270, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2nd (2).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(320, 90, 280, 370);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(560, 0, 810, 950);

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(107, 0, 215));
        jLabel16.setText("Username :");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(160, 150, 110, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Coloring dark1 (1).jpg"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, -10, 660, 720);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 30, 1370, 940);

        jPanel1.setBackground(new java.awt.Color(107, 0, 215));
        jPanel1.setLayout(null);

        jLabelClose.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelClose.setText("X");
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose);
        jLabelClose.setBounds(1338, 0, 10, 30);

        jLabelMin.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabelMin.setText("-");
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMin);
        jLabelMin.setBounds(1310, 0, 8, 27);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1370, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked

        System.exit(0);

    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked

        this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jTextFieldLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLastnameActionPerformed

    private void jTextFieldFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstnameActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed

        String fname = jTextFieldFirstname.getText();
        String lname = jTextFieldLastname.getText();
        String username = jTextFieldUsername.getText();
        String email = jTextFieldEmail.getText();
        String phoneno = jTextFieldPhonenum.getText();
        String manager = jTextFieldManager.getText();
        String project = jTextFieldProject.getText();

Date dueDate = jDateChooserDue.getDate(); // Get the Date object

String due = null; // Initialize due as null
if (dueDate != null) {
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // Customize the date format as needed
    due = dateFormat.format(dueDate); // Convert the Date to String
}

String gender = "Male";

if (jRadioButtonFemale.isSelected()) {
    gender = "Female";
}

if (verifyFields()) {
    if (!checkUsername(email)) {
        PreparedStatement ps;
        ResultSet rs; // Corrected "Resultset" to "ResultSet"
        String addUserQuery = "INSERT INTO crud(firstname, lastname, username, email, phoneno, gender, manager, project, due)VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";


        try {
            ps = My_CNX.getConnection().prepareStatement(addUserQuery);
            ps.setString(1, fname);
            ps.setString(2, lname);
            ps.setString(3, username);
            ps.setString(4, email);
            ps.setString(5, phoneno);
            ps.setString(6, gender);
            ps.setString(7, manager);
            ps.setString(8, project);
            ps.setString(9, due);

            // Save the image as Blob in the database

            if (ps.executeUpdate() != 0) {
                JOptionPane.showMessageDialog(null, "Add account complete");
            } else {
                JOptionPane.showMessageDialog(null, "Error Check your Information");
            }

        } catch (SQLException ex) {
            Logger.getLogger(AddAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
        
        
        
        
        
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jLabelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseClicked
        LandForm2 rgf = new LandForm2();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelLoginMouseClicked

    private void jButtonAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddMouseEntered
        
         jButtonAdd.setBackground(new Color(88,0,178));
        
    }//GEN-LAST:event_jButtonAddMouseEntered

    private void jButtonAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddMouseExited
      
         jButtonAdd.setBackground(new Color(138,25,255));
        
    }//GEN-LAST:event_jButtonAddMouseExited

    private void jTextFieldFirstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFirstnameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstnameFocusGained

    private void jTextFieldFirstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFirstnameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstnameFocusLost

    private void jTextFieldLastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLastnameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLastnameFocusGained

    private void jTextFieldLastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLastnameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLastnameFocusLost

    private void jTextFieldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailFocusGained

    private void jTextFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailFocusLost

    private void jTextFieldPhonenumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhonenumFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhonenumFocusGained

    private void jTextFieldPhonenumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhonenumFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhonenumFocusLost

    private void jRadioButtonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMaleActionPerformed

    private void jTextFieldProjectFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProjectFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProjectFocusGained

    private void jTextFieldProjectFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProjectFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProjectFocusLost

    private void jTextFieldUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsernameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameFocusGained

    private void jTextFieldUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsernameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameFocusLost

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jTextFieldManagerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldManagerFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldManagerFocusLost

    private void jTextFieldManagerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldManagerFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldManagerFocusGained

    public boolean verifyFields()
    {
    String fname = jTextFieldFirstname.getText();
    String lname = jTextFieldLastname.getText();
    String username = jTextFieldUsername.getText();
    String email = jTextFieldEmail.getText();
    String phoneno = jTextFieldPhonenum.getText();
    String manager = jTextFieldManager.getText();
    String project = jTextFieldProject.getText();
 
    Date dueDate = jDateChooserDue.getDate();
    String due = null; // Initialize due as null
    if (dueDate != null) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // Customize the date format as needed
        due = dateFormat.format(dueDate);
    }

    
    if(fname.trim().equals("") || lname.trim().equals("")|| email.trim().equals("")|| phoneno.trim().equals("")|| 
        manager.trim().equals("") || project.trim().equals("")) 
               
       {
        JOptionPane.showMessageDialog(null, "One or more fields are empty", "Empty Fields", 2);
         return false;
       }
        else{
               
        return true;
       }
    }
    
         public boolean checkUsername(String username){
        
        PreparedStatement st;
        ResultSet rs;
        boolean email_exist = false;
        
        String query = "SELECT * FROM crud WHERE email =?";
        
        try {
            st = My_CNX.getConnection().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
            
        } catch (SQLException ex) {
            Logger.getLogger(AddAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return email_exist;
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JCheckBox jCheckBox1;
    private com.toedter.calendar.JDateChooser jDateChooserDue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirstname;
    private javax.swing.JTextField jTextFieldLastname;
    private javax.swing.JTextField jTextFieldManager;
    private javax.swing.JTextField jTextFieldPhonenum;
    private javax.swing.JTextField jTextFieldProject;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables

    private boolean checkEmail(String email) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


}
